name = "dj-booking"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Variables d'environnement
[env.production]
route = "events.cax-corp.com/*"
zone_id = "your-zone-id-here"

[[env.production.kv_namespaces]]
binding = "RESERVATIONS_KV"
id = "6ec7797b14b04e5a999a2b794bd906d7"

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "dj-booking-assets"

[env.production.vars]
ENVIRONMENT = "production"

# Secrets (Webhook Discord)
# Ajouter via: wrangler secret put DISCORD_WEBHOOK